name: Package PLG
on:
  push:
    branches:
      - dev
jobs:
  pull_and_edit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Update MD5 and date in plg file
        shell: bash
        run: |
          #!/bin/bash
          wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/main/plugin.sh
