name: Package PLG
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container: spaceinvaderone/auto_slack_pack
    env:
      name: "bobbintb.system.dedupe"
      author: "bobbintb"
      repo: "UnRAID-DeDuper"
      launch: "Settings/Dedupe"
      pluginURL: "https://raw.githubusercontent.com/&author;/&repo;/master/&name;.plg"
      source: "/boot/config/plugins/&name;/&name;"
      icon: "fa-search-minus"
      min: "6.1.9"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download UnRAID-Plugin-Generator
        run: |
          wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/main/plugin.sh
          chmod +x plugin.sh
      - name: Run UnRAID-Plugin-Generator
        run: |
          ./plugin.sh
          rm plugin.sh
          ls -ls
