name: Package TXZ and update PLG
on:
  push:
    branches:
      - master
jobs:
  pull_and_edit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Package plugin as txz
        shell: bash
        run: |
          #!/bin/bash
          echo "Current working directory:"
          pwd
          ls -l
          echo "Creating folder structure..."
          dest="../src/usr/local/emhttp/plugins/bobbintb.system.dedupe"
          mkdir -p "$dest"
          echo "Copying files to temporary folder to archive..."
          ls -l
          cp -r ./src/* $dest
          echo "Archiving..."
          ls -l ../src
          7z a -ttar -so -an ../src/usr | 7z a -txz -si bobbintb.system.dedupe.txz
          mv bobbintb.system.dedupe.txz ./artifacts
          #rm -rf $dest
      - name: Update MD5 and date in plg file
        shell: bash
        run: |
          #!/bin/bash
          txz="./artifacts/bobbintb.system.dedupe.txz"
          plg="./artifacts/bobbintb.system.dedupe.plg"
          curdate=$(date +"%Y.%m.%d")
          echo "Current date: ${curdate}"
          pattern='ENTITY MD5\s+"([^"]+)"'
          datepattern='ENTITY version\s+"([^"]+)"'
          last_plg=$(wget -O - https://github.com/bobbintb/UnRAID-DeDuper/raw/release/artifacts/bobbintb.system.dedupe.plg)
          previousVersion=$(echo "$last_plg" | grep -o -m 1 -P "$datepattern" | awk -F '"' '{print $2}')
          echo "Previous version: ${previousVersion}"
          if [[ $curdate == $previousVersion ]]; then
          curdate+="a"
          echo "New version: ${curdate}"
          fi
          if [[ $curdate == ${previousVersion%?} && "$previousVersion" =~ [[:alpha:]]$ ]]; then
          extracted_letter=${previousVersion: -1}
          echo "Previous sub-version: ${extracted_letter}"
          ascii_code=$(printf "%d" "'$extracted_letter")
          next_ascii_code=$((ascii_code + 1))
          next_letter=$(printf \\$(printf '%03o' "$next_ascii_code"))
          curdate+=next_letter
          echo "New version: ${curdate}"
          fi
          md5Hash=$(md5sum "$txz" | awk '{print $1}')
          content=$(<"$plg")
          newContent=$(echo "$content" | sed -E "s/$datepattern/ENTITY version   \"$curdate\"/" | sed -E "s/$pattern/ENTITY MD5       \"$md5Hash\"/")
          echo "$newContent" > "$plg"
      - name: Git Commit 
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Updated plg and txz files"
          git add ./artifacts/bobbintb.system.dedupe.txz
      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: release
          force: true

