name: Package TXZ and update PLG
on:
  push:
    branches:
      - master
jobs:
  pull_and_edit:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow should stop
        if: ${{ github.ref_type == 'tag' && github.ref != 'refs/tags/release' }}
        run: |
          echo "Workflow stopped because it was triggered by the bot."
          exit 0
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Package plugin as txz
        shell: bash
        run: |
          #!/bin/bash
          echo "Current working directory:"
          pwd
          ls -l
          echo "Creating folder structure..."
          dest="../src/usr/local/emhttp/plugins/bobbintb.system.dedupe"
          mkdir -p "$dest"
          echo "Copying files to temporary folder to archive..."
          ls -l
          cp -r ./src/* $dest
          echo "Archiving..."
          ls -l ../src
          7z a -ttar -so -an ../src/usr | 7z a -txz -si bobbintb.system.dedupe.txz
          mv bobbintb.system.dedupe.txz ./artifacts
          #rm -rf $dest
      - name: Update MD5 in plg file
        shell: bash
        run: |
          #!/bin/bash
          txz="./artifacts/bobbintb.system.dedupe.txz"
          plg="./artifacts/bobbintb.system.dedupe.plg"
          md5Hash=$(md5sum "$txz" | awk '{print $1}')
          pattern='ENTITY MD5\s+"([^"]+)"'
          content=$(<"$plg")
          newContent=$(echo "$content" | sed -E "s/$pattern/ENTITY MD5       \"$md5Hash\"/")
          echo "$newContent" > "$plg"
      - name: Git Commit 
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Updated plg and txz files"
      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}

