name: Pull and Edit

on:
  workflow_dispatch:

jobs:
  pull_and_edit:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Package plugin as txz
        shell: cmd
        run: |
          @echo off
          set "dest=./usr\local\emhttp\plugins\bobbintb.system.dedupe"
          mkdir "%dest%"
          robocopy ./src "%dest%" /E /XF bundle.bat /XF bobbintb.system.dedupe.plg /XF deduper.db /XF query.txt /XF .gitignore /XF *.yml /XD usr .git .vs
          7z.exe a -ttar -so -an ./usr | 7z.exe a -txz -si ./artifacts\bobbintb.system.dedupe.txz
          rd /s /q usr
      - name: Edit file with PowerShell
        shell: powershell
        run: |
          # Set the path to your file
          $file = "./artifacts\bobbintb.system.dedupe.plg"
          $md5Hash = ((Get-FileHash -Path $file -Algorithm MD5).Hash).ToLower()
          # Read the file contents
          $content = Get-Content -Path $file

          # Define the regular expression pattern to match the text within quotes
          $pattern = 'ENTITY MD5\s+"([^"]+)"'

          # Find and replace the text within quotes
          $newContent = $content -replace $pattern, "ENTITY MD5       `"$md5Hash`""


          # Write the modified content back to the file
          $newContent | Set-Content -Path $file

      - name: Commit and push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add ./artifacts\bobbintb.system.dedupe.plg
          git add ./artifacts\bobbintb.system.dedupe.txz
          git commit -m "Updated file"
          git push
