name: Pull and Edit

on:
  workflow_dispatch:

jobs:
  pull_and_edit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Edit file
        run: |
          @echo off
          set "dest=./usr\local\emhttp\plugins\bobbintb.system.dedupe"
          mkdir "%dest%"
          robocopy ./src "%dest%" /E /XF bundle.bat /XF bobbintb.system.dedupe.plg /XF deduper.db /XF query.txt /XF .gitignore /XF *.yml /XD usr .git .vs
          7z.exe a -ttar -so -an ./usr | 7z.exe a -txz -si $(Build.SourcesDirectory)\artifacts\bobbintb.system.dedupe.txz
          rd /s /q usr

      - name: Commit and push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Updated file"
          git push
