name: Package PLG
on:
  push:
    branches:
      - dev
jobs:
  package_and_update:
    if: github.event.commits[0].author.name == 'bobbintb'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}
      - name: Download UnRAID-Plugin-Generator
        run: |
          wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/main/plugin.sh
          chmod +x plugin.sh
      - name: Run UnRAID-Plugin-Generator
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          ./plugin.sh
          rm plugin.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Armando
          author_email: bobbintb@gmail.com
          message: ${{ github.event.head_commit.message }}
          add: 'bobbintb.system.dedupe.plg bobbintb.system.dedupe.txz'
